export default {
    title: "Povestea lui Harap-Alb - Ion Creangă",
    text: `SPECIĂ: basm cult
CURENT LITERAR: realism
ÎNCADRARE ISTORICĂ: perioada clasicilor mari (secolul al XIX-lea)
ANUL APARIȚIEI: publicat în revista „Convorbiri literare”, în anul 1877

TEMA: confruntarea dintre cele două principii fundamentale opuse: binele și răul, cu victoria celui dîntâi, de fapt o supratemă pe care se grefează romanul unei inițieri (bildungsroman).

CUPRINS
1. Eseu general „Povestea lui Harap-Alb” de Ion Creangă
2. Relaţia dintre incipit şi final
3. Caracterizare Harap-Alb
4. Eseu: Relaţia dintre două personagem
5. Subiecte Bacalaureat Subiectul al III-lea: Basmul cult


1. ESEU GENERAL „POVESTEA LUI HARAP-ALB” DE ION CREANGĂ

Tema şi viziunea despre lume / Particularităţi de structură, compoziţie şi limbaj în basmul cult „Povestea lui Harap-Alb” de Ion Creangă.

Literatura română din a doua parte a secolului al XIX-lea se detaşează prin promovarea unei literaturi autentice, care să înlocuiască "formele fără fond", aspect evidenţiat de scrierile celor patru mari clasici: Mihai Eminescu, Ion Creangă, I.L. Caragiale şi Ioan Slavici.

Apărută în anul 1877 în revista „Convorbiri literare“, opera lui Ion Creangă intitulată „Povestea lui Harap-Alb“ este un basm cult (detașându-se de cel popular prin: individualizarea personajelor prin limbaj, îmbinarea armonioasă a modurilor de expunere și originalitatea limbajului povestitorului humuleștean), specie a genului epic în proză, pluriepisodică, în care personajele reale sau fantastice sunt purtătoare de valori simbolice, iar lupta dintre bine şi rău se finalează de obicei cu victoria binelui. În „Estetica basmului“, criticul literar George Călinescu defineşte basmul ca „un gen vast, depăşind cu mult romanul, fiind mitologie, etică, ştiinţă, observaţie morală“. Ceea ce se remarcă mai presus de orice la basmele lui Creangă este realismul caracteristic acestora, fapt susţinut şi de Nicolae Manolescu în lucrarea „Lecturi infidele“, care menţionează că ele „nu sunt rescrise, împodobite, alterate în structura lor“, reflectând realitatea imediată. Acestuia i se adaugă planul miraculos, extraordinar, cele două coordonate (real - ireal) împletindu-se astfel într-o formă inovativă, conferind o viziune epică originală.

Având ca sursă de inspiraţie basmul popular, autorul ilustrează mituri străvechi universale, dar mai ales autohtone, înglobând în textul de faţă toată „filosofia noastră populară“ (Pompiliu Constantinescu – „Scrieri“). Motivele identificabile sunt specifice mitologiei, precum cel al superiorităţii mezinului, al călătoriei şi al probelor inițiatice.

Tema operei, pe lângă cea specifică aceastăi specii literare, şi anume a luptei dintre bine şi rău, este cea a maturizării mezinului craiului, vizibilă încă din titlu. La nivel morfologic, titlul este constituit din substantivul comun „Povestea”, articularea acestuia arătând singularitatea istorisirii, atribuită în continuare prin utilizarea substantivului propriu, lui Harap-Alb. „Povestea” marchează caracterul de bildungsroman al scrierii, aceasta prezentând pe parcursul său evoluţia personajului principal din ipostaza de tânăr neiniţiat în cea de împărat. Denumirea de Harap-Alb provine dintr-un oximoron (harap = slugă de culoare neagră, alb = culoare ce sugerează caracterul nobil), subliniind astfel ironia în momentul în care crăişorul devine supusul Spânului și primeşte acest apelativ din partea noului stăpân. Viziunea despre lume a povestitorului susţine faptul că omul "de soi bun" îşi atinge obiectivele, scopurile stabilite de divinitate, cu ajutorul semenilor, dar mai ales datorită virtuţilor morale: generozitate, onoare, simţul datoriei, respect.

Acţiunea basmului este relatată prin prisma unei perspective narative obiective, însoţită de o viziune dindărăt, de către un narator omniscient şi omniprezent, a cărui obiectivitate este contestabilă întrucât există numeroase intervenţii şi comentarii pe parcursul relatării, caracterizate prin umor şi oralitate. Modul de expunere predominant este naraţiunea la persoana a III-a, ce alternează cu dialogul.

Contextul spaţio-temporal este tipic basmului, reperele fiind vagi, neputând fi determinate. Întâmplările se desfăşoară într-un timp nedefinit ("illo tempore"), adverbele folosite pentru a preciza acest aspect fiind „odată”, „cândva”, „atunci”. Încă din incipit, naratorul plasează acțiunea într-un prezent fictiv „Amu”. Se remarcă şi imprecizia spaţiului „undeva”, „într-o pădure”, „în grădina ursului”, acţiunea începând la „o margine a pământului” şi terminându-se la alta, toposuri corespunzătoare pentru împărăţiile celor două familii. Spre deosebire de basmele populare, nu sunt prezente tărâmuri strict delimitate ce aparţin forţelor binelui sau ale răului.

Conflictul aparţine tot universului basmului, fiind unul de natură exterioară, între forţele binelui şi cele ale răului, avându-i ca exponenţi pe Harap-Alb şi Spân, antrenaţi pe tot parcursul operei în diverse întâmplări ce duc în final la biruinţa celui devenit împărat.

În structura creaţiei epice se poate identifica o simetrie între incipit şi final, realizată prin formule caracteristice speciei literare, acestea delimitând spaţiul fantastic: „Amu cică era odată într-o țară” - „Şi a ținut veselia ani întregi, și acum mai ține încă”. Întâmplările relatate se desfăşoară ordonat, logic, prin înlănţuirea episoadelor. Există trei planuri narative ce corespund celor trei etape din evoluţia personajului eponim. Astfel, un prim plan narativ este cel de la curtea craiului în care acesta este doar un tânăr lipsit de experienţă, al doilea este reprezentativ pentru încercările la care este supus la curtea lui Verde Împărat, aflându-se sub controlul Spânului, în vreme ce în al treilea, tânărul, ajutat de creaturile fantastice, se căsătoreşte cu domniţa.

Ca în orice operă narativă, acţiunea este împărţită pe momentele subiectului ce corespund unui tipar narativ. Expoziţiunea, situaţia inițială de echilibru, prezintă familia Craiului, alcătuită din tatăl şi cei trei fii. Sunt precizate şi reperele spaţio-temporale, ambigue. Intriga sau factorul perturbator, momentul ce determină un dezechilibru şi declanşează următorul moment important, desfăşurarea acţiunii, este reprezentată de primirea unei scrisori de la fratele Craiului, Verde Împărat, care, aflându-se într-o stare precară de sănătate, cere să-i fie trimis unul dintre feciori pentru a-i lua locul.

În continuare, fiii cei mari îşi încearcă norocul, însă nu reuşesc să treacă de una din probele introduse de tatăl lor cu scopul de a-i testa, respectiv cea a podului. Decepţionat de reacţia tatălui la eşecul predecesorilor săi, mezinul este ajutat de Sfânta Duminică în dobândirea curajului necesar întreprinderii călătoriei, facilitat de calul, straiele şi armele deţinute anterior de tatăl său. Se remarcă în acest sens motivul superiorităţii mezinului, singurul care a reuşit să treacă peste proba de la pod, simbol pentru pătrunderea într-o altă etapă a vieţii. După ce primeşte sfatul bătrânului: „În călătoria ta să ai trebuinţă şi de răi şi de buni, dar să te fereşti de omul roş, iar mai ales de cel Spân cât îi putea”, fatalitatea se produce şi crăişorul se rătăceşte în drumul său, având nevoie de spânul pe care îl întâlnise. Odată cu coborârea mezinului în fântână are loc transformarea acestuia în sluga Spânului, odată cu noul apelativ. Urmează trei probe la care Harap-Alb este supus de stăpân şi pe care, cu ajutorul unor personnage fantastice (albinele, calul, furnicile, Ochilă, Gerilă, Setilă, Flămânzilă şi Păsări-Lăţi-Lungilă) le duce la bun sfârşit. Sub simbolul cifrei magice trei, probele sunt: aducerea salatelor din Grădina Ursului, a pieii cu pietre preţioase din Pădurea Cerbului şi a fetei Împăratului Roş - probă ce implică alte probe: casa de aramă, ospățul pantagruelic, alegerea macului de nisip, păzirea fetei, ghicirea acesteia, întrecerea dintre cal și turturică (pentru a aduce trei smicele de măr dulce).

Punctul culminant sau acțiunea reparatorie, este atins în momentul în care Harap-Alb se întoarce triumfător la curtea Împăratului Verde cu domniţa. Spânul este demascat şi drept răzbunare, încearcă să-l omoare pe Harap-Alb, fără a avea succes, fata de împărat readucându-l la viaţă după tăierea capului, marcând astfel dezvoltarea completă a crăişorului.

Deznodământul este înfăţişat de refacerea echilibrului în universul imaginar şi nunta tânărului cu fata împăratului Roş, confirmând atingerea maturităţii.

Personajele create de Ion Creangă sunt diferite reprezentări ale binelui şi ale răului. Protagonistul beneficiază pe tot parcursul călătoriei sale iniţiatice de ajutoare: fiinţe ce deţin puteri fantastice (înţeleapta Sfânta Duminică), animale fabuloase (calul, furnicile, albinele), fiinţe himerice (cele cinci creaturi extraordinare) şi obiecte miraculoase (aripile crăieselor, apa vie, apa moartă). Antagonistul este cel pe care trebuie să-l confrunte în vederea evoluţiei.

Harap-Alb, apelativ dobândit graţie Spânului, dovedeşte o serie de calităţi umane obligatorii pentru a devenit conducătorul unui tărâm, precum bunătatea, mila („eşti aşa bun de ţi-a fost milă de viaţa noastră”), adaptabilitatea, curajul („dar pe urmă venindu-i inima la loc şi plin de încredere în sine”), onoarea, respectarea jurămintelor, simţul responsabilităţii. Acestuia nu îi sunt atribuite trăsături neobişnuite, personajul fiind construit atipic, dar pe un tipar realist.

Spânul, personajul opus din punct de vedere al portretului moral, este dominat de răutate, însă este un rău necesar, esenţial în acumularea de experienţă pentru crăişor, fapt admis şi de cal: „Şi unii ca aceştia sunt trebuitori pe lume câteodată, pentru că fac pe oameni să prindă la minte”. El poate fi încadrat în tipologia omului viclean, manipulator, expert în arta disimulării.

Mijloacele de caracterizare a personajelor sunt directe - prin intervenţiile naratorului, aportul altor personaje şi autocaracterizare - şi indirecte – reieşind din fapte, reacţii, gânduri, relaţiile cu alte personaje, nume.

Lumea lui Creangă este una autentic ţărănească pe care o satirizează cu mijloacele basmului, dat fiind faptul că personajele au un comportament individual şi indiferent de rangul pe care îl posedă, acestea vorbesc la fel, într-o manieră specifică lumii rurale. Stilul autorului este caracterizat de plăcerea, verva de a nara, realizată prin umor și jovialitate. Se remarcă poreclele şi apelativele caricaturale (Buzilă, “mangosiţi”), ironia: „Doar unu-i împăratul Roş, vestit pentru bunătatea lui cea nemaipomenită şi milostivenia lui cea auzită”. Zeflemisirea este de asemenea prezentă: „Tare-mi eşti drag, te-aş vârî în sân, dar nu-mi încapi de urechi.”, împreună cu diminutivele folosite cu valoare augmentativă: „băuturică”, „buzişoare”.

Autorul citează la tot pasul zicători, proverbe şi vorbe de duh (de exemplu: „Dă-i cu cinstea să piară ruşinea”) pe care le preia din tezaurul popular şi le introduce în discursul narativ prin sintagma „Vorba ceea”, dând dovadă de erudiţie paremiologică.

Ion Creangă reuşeşte să îmbine elemente ce aparţin fabulosului cu altele aparţinând realismului, într-o simbioză literară inedită, surprinzând drumul protagonistului spre desăvârşirea personalităţii. Acesta se inspiră din folclor şi relatează întâmplările într-o manieră proprie, guvernată de umor şi bucuria de a povesti, cu scopul de a sublinia caracterul moralizator al scrierilor sale.

În concluzie, "Povestea lui Harap-Alb" este un basm cult întrucât prezintă caracteristicile definitorii ale aceastăi specii, concentrându-se pe tema luptei dintre bine şi rău, din care biruitor este binele, și mai ales pe cea a maturizării eroului, prezentând totodată formule, simboluri şi motive specifice.


2. RELAŢIA DINTRE INCIPIT ŞI FINAL ÎNTR-UN BASM CULT STUDIAT

Eseu despre relaţia dintre incipit şi final într-un basm cult studiat.

Basmul este o naraţiune deliberat fantastică, definită ca specie a genului epic din literatura populară sau cultă, care prezintă confruntarea dintre două categorii opuse – Binele şi Răul -, simbolizate prin personaje pozitive şi negative. Din această confruntare, Binele iese învingător, deoarece basmul propune modele de conduită, idealuri preţuite de omul din popor. Din literatura populară, specia a trecut şi în literatura cultă, basmul cult exprimând viziunea artistică a unui singur creator.

Ion Creangă, unul dintre scriitorii care s-au impus în literatura română prin originalitatea stilului, a lăsat posterităţii o operă variată, aducând în literatura cultă farmecul şi spontaneitatea literaturii populare. „Povestea lui Harap-Alb”, considerată „sinteză a basmului românesc” (Nicolae Ciobanu), se dezvoltă pe un tipar narativ tradiţional, particularizat prin intervenţiile autorului cult, care supune materialul epic unui proces de transformare în funcţie de propriile structuri mentale şi de propriile concepţii. Tema acestui basm cult depăşeşte limitele unei simple confruntări între bine şi rău, pentru că se urmăreşte procesul amplu de maturizare a unui erou care parcurge un complex drum iniţiatic.

Incipitul basmului lui Ion Creangă elimină schematismul enunţiativ specific prototipului folcloric umplând de conţinut atemporalitatea şi aspaţialitatea convenţiei prototipale: „Amu cică era odată într-o ţară un craiu, care avea trei feciori…” Situarea in illo tempore a acţiunii, din basmele populare, prin convenţionala formulă din incipit – „A fost odată ca niciodată, că dacă n-ar fi nu s-ar povesti…” –, dobândeşte, în basmul lui Ion Creangă, semnificaţii aparte. Incipitul anunţă o viziune particulară asupra universului imaginar, pe care îl pune sub semnul ironic al improbabilităţii: „Amu cică…” Cu alte cuvinte, încă de la începutul basmului, cititorul este invitat să pună sub semnul jocului „lumea pe dos” pe care o prezintă autorul cult. Regionalul „amu” aduce în lumea prezentă a cititorului lumea atemporală a basmului, ceea ce echivalează cu o eternizare a lecţiei de viaţă pe care autorul intenţionează să o prezinte. Perspectiva narativă obiectivă e subminată, încă din incipit, prin sugestia unei prezenţe a vocii narative, care creează o relaţie între timpul discursului – „Amu cică era odată…” – şi timpul istoriei – „Amu cică împăratul acela, aproape de bătrâneţe, căzând la zăcare…” De remarcat, ca o particularitate a incipitului din basmul cult al lui Ion Creangă, supradimensionarea expoziţiunii, care îndeplineşte rolul clasic al prezentării personajelor şi al circumstanţelor acţiunii – craiul, care are trei fii, Împăratul Verde, care are trei fiice, războaiele grele care despart cele două împărăţii şi care justifică înstrăinarea fraţilor şi a copiilor -, dar are şi elemente de modernitate, reliefând vocea narativă, care îl va însoţi constant, de-a lungul acţiunii, pe cititor, interpretând şi comentând evenimentele: „de aceea nu se putea călători aşa de uşor şi fără primejdii ca în ziua de astăzi.” Reluarea firului narativ după prezentarea personajelor şi a situaţiei iniţiale se realizează prin intervenţia naratorului în istorie: „Dar ia să nu ne depărtăm cu vorba şi să încep a depăna firul poveştii”.

Din acest punct al relatării, construcţia subiectului este liniară, episoadele se structurează prin înlănţuire, acţiunile decurg firesc una din cealaltă şi se motivează reciproc. Timpul şi spaţul acţiunii sunt imaginare, chiar dacă au elemente care amintesc de universul obişnuit. Întâmplările se petrec odată, cândva, atunci, adverbele sugerând un timp nedefinit, rupt de cel cotidian. Atemporalităţii acţiunii îi corespunde imprecizia spaţiului – undeva, într-o pădure, în grădina ursului.

Acţiunea basmului este structurată pe episoade, urmărind tiparele epicii populare. Situaţia iniţială prezintă o stare de echilibru – craiul are trei feciori, Verde-Împărat are trei fete - care va fi perturbat prin sosirea scrisorii lui Verde-Împărat. Acesta nu are moştenitori şi îi cere fratelui său să îi trimită pe unul dintre fii pentru a-i lăsa împărăţia. Rugămintea nu e deloc uşor de îndeplinit, pentru că cele două împărăţii se află departe una de cealaltă, separate de războaie.

Acţiunea de recuperare a echilibrului, care constituie un alt element din tiparul narativ tradiţional, începe în momentul în care fiii mai mari ai craiului pornesc spre împărăţia unchiului lor, convinşi că vor reuşi. Ambii eşuează lamentabil la proba podului, unde sunt aşteptaţi de tatăl deghizat în piele de urs. Mezinul va pleca în aceeaşi călătorie, după ce va dobândi, cu ajutorul sfaturilor Sfintei Duminici, calul cu puteri supranaturale, hainele şi armele tatălui său din tinereţe. Proba podului va fi depăşită cu ajutorul calului, iar motivul călătoriei iniţiatice, specific basmelor, se asociază cu sfaturile tatălui, care îi cere fiului să se ferească de omul spân şi de omul roş, dăruindu-i pielea de urs.

Probele la care va fi supus eroul ulterior sunt, de asemenea, trepte ale iniţierii. La trecerea prin pădurea-labirint, fiul craiului se rătăceşte şi acceptă, după trei întâlniri fatidice, tovărăşia omului spân. Spânul, spre deosebire de personajele negative tipice din basmele populare, adoptă un comportament care nu se abate cu nimic de la legile firescului. Prin vicleşug, la fântână, acesta îşi însuşeşte identitatea crăişorului, momentul fiind echivalent cu un adevărat botez, întrucât fiul craiului primeşte un nume – Harap-Alb – şi o nouă identitate – slugă a Spânului.

Procesul iniţiatic din „Povestea lui Harap-Alb” este mult mai complicat şi include parcurgerea unor etape complexe, marcând simbolic drumul spre maturitate al eroului. După ce ajung la Verde-Împărat, Harap-Alb este trimis să aducă salatele nemaiîntâlnite din Grădina Ursului, probă pe care o depăşeşte cu ajutorul calului şi al Sfintei Duminici. A doua probă la care este supus eroul este una a maturizării voinţei. Nestematele cerbului din pădurea fermecată nu pot fi dobândite decât de acela care ascultă fără şovăire sfaturile Sfintei Duminici. A treia probă este şi cea mai dificilă. Spânul cere să-i fie adusă fata Împăratului Roş pentru a o lua de soţie. Această probă presupune alt drum iniţiatic, cu mai multe etape. La curtea Împăratului Roş, Harap-Alb şi însoţitorii săi trebuie să facă faţă altor provocări pentru a dobândi mâna fetei: proba ospăţului, înnoptatul în casa înroşită de foc, alegerea macului de nisip, păzirea şi prinderea fetei, identificarea acesteia. Ultima probă constă în aducerea apei vii, a apei moarte şi a celor trei smicele de măr dulce. Întoarcerea la curtea lui Verde-Împărat marchează şi ultima etapă a maturizării eroului, de natură afectivă. Harap-Alb se îndrăgosteşte de fata Împăratului Roş şi nu ar vrea să i-o dea Spânului, cum a procedat cu trofeele dobândite în cursul celorlalte probe. Restabilirea echilibrului se realizată prin dezvăluirea adevăratei identităţi a eroului. Spânul îi taie capul lui Harap-Alb, iar calul îl omoară pe uzurpator, ridicându-l până în înaltul cerului, de unde îi dă drumul. Este, de altfel, una dintre puţinele situaţii în care calul îşi dezvăluie adevăratele puteri. Fata Împăratului Roş recompune trupul eroului, îl descântă, readucându-l la viaţă, element echivalent cu o renaştere, care presupune dobândirea noii identităţi, de stăpân.

Basmul cult aduce inovaţii structurii basmului popular prin multiplicarea numărului probelor la care este supus eroul şi prin complicarea lor progresivă până la deznodământul tipic. Personajul principal nu mai este învestit cu calităţi excepţionale ca în basmul popular, nu mai are puteri neobişnuite, capacitatea de a se metamorfoza şi are un caracter complex, reunind calităţi şi defecte. De aici, autenticitatea umană pe care o dobândeşte eroul şi care îi conferă un caracter aparte. Deşi aparţine tipologiei voinicului din poveste, căruia îi este caracteristic atributul invincibilităţii necondiţionate, asigurată de miraculoasa lui putere, Harap-Alb este departe de tiparele convenţionale. Autorul îl construieşte accentuându-i latura umană – este şovăitor în faţa deciziilor sau gata să se lase stăpânit de frică, naiv, copleşit de rolul pe care şi l-a asumed. Se distinge printr-o calitate excepţională, care îl impune ca erou exemplar: bunătatea. Personajele auxiliare care i se alătură eroului datorită aceastăi calităţi – Sfânta Duminică, calul năzdrăvan, furnicile, albinele, giganţii fabuloşi – extind această calitate dominantă a eroului în sfera întregului univers.

La nivel formal, scenariul epic este încadrat de formulele specifice: iniţiale – „Amu cică era odată un crai…” -, mediane – „Dumnezeu să ne ţie, ca cuvântul din poveste, înainte mult mai este” -, finale – „Şi a ţinut veselia ani întregi, şi acum mai ţine încă; cine se duce acolo be şi mănâncă. Iar pe la noi, cine are bani bea şi mănâncă, iar cine nu, se uită şi rabdă”.

În acelaşi spirit inovator ca şi incipitul, finalul este realizat în doi timpi. Deznodământul acţiunii nu coincide cu finalul operei, accentuând prezenţa ludică a naratorului, voce a autorului distinctă în relatare în acest basm, care completează, atenţionează, comentează. Aşadar, deznodământul e unul tipic pentru specie: „Şi au mai fost poftiţi încă: crai, crăiese şi-mpăraţi, oameni în samă băgaţi, ş-un păcat de povestariu, fără bani în buzunariu. Veselie mare între toţi era, chiar şi sărăcimea ospăta şi bea!” Finalul însă, concentrează întregul şi îi aparţine naratorului omniscient, care face legătura dintre timpul basmului şi timpul cititorului, creând corespondenţa dintre ficţiune şi realitate şi sintetizând, amar-ironic, trăsăturile realităţii: „Şi a ţinut veselia ani întregi, şi acum mai ţine încă; cine se duce acolo be şi mănâncă. Iar pe la noi, cine are bani bea şi mănâncă, iar cine nu, se uită şi rabdă.” Sintagma „pe la noi” nu face trimitere numaidecât la lumea contemporană autorului, ci la lumea din afara basmului, posibilă oricând şi oriunde. Se remarcă, din nou, suprapunerea timpului istoriei cu timpul discursului, semn că intenţia principală a naratorului este de a transmite o anumită viziune despre lumea pe care a făcut-o să trăiască sub ochii cititorului.

Cititorul este reintrodus în realitatea din care a plecat fără menajamente, semn că jocul s-a terminat şi că magia spunerii a luat sfârşit. Din perspectiva raportului cu realitatea, incipitul şi finalul basmului cult al lui Ion Creangă se înscriu într-o relaţie de simetrie. Prin iniţialul „Amu cică”, naratorul pune un pariu cu sine – acela de a-l face pe cititor să uite de propria lume şi să se delecteze cu povestea „de mirare” a lui Harap-Alb şi a tovarăşilor săi. În final, cititorului i se reaminteşte că lumea din care a ieşit temporar e una a contrastelor. Dar, în ciuda realismului lumii sale, cititorul a aflat, prin parcurgerea poveştii, că poate evada oricând în lumea „de poveste”, care îmbină desăvârşit datele lumii ficţiunii cu datele lumii de „pe la noi”.


3. CARACTERIZARE HARAP-ALB

Eseu de caracterizare a personajului principal din basmul cult studiat.

Literatura română din a doua parte a secolului al XIX-lea se detașează prin promovarea unei literaturi autentice care să înlocuiască ”formele fără fond”, aspect evidențiat de scrierile celor patru mari clasici: Mihai Eminescu, Ioan Slavici, Ion Luca Caragiale și Ion Creangă. Operele lui Creangă se detașează ca fiind originale prin realismul de esență folclorică ce se îmbină cu fabulosul, prezentând personaje fantastice sau din realitatea lumii țărănești, caracteristică ce se remarcă cu precădere în basmele sale, fiind numit chiar inițiatorul basmului cult în literatura românească.

”Povestea lui Harap-Alb” este un basm cult publicat în revista ”Convorbiri literare” în anul 1877, reprezentând, după cum considera în ”Scrieri” Pompiliu Constantinescu ”însăşi sinteza basmului românesc”. Bazându-se pe modelul și pe sursele de inspirație ale basmelor populare, cel cult reprezintă dezvoltarea unor trăsături precum clișeele compoziționale, motivele narative, elementele de cronotop, dar individualizează personajele prin limbaj, umor și oralitate. În basmul ”Povestea lui Harap-Alb”, este dezvoltată paradigma mentor-învățăcel ca fundament al evoluției caracterului uman și este reprezentată simbolic prin tema inițierii. Aceasta este generată de nevoia unui parcurs spiritual, în urma căruia cel inițiat capătă acces la cunoașterea lumii și a descoperirii de sine.

Eroul basmului ”Povestea lui Harap-Alb” urmează o evoluție tipică temei maturizării prin intermediul drumului inițiatic întrucât suplinește nevoia unei evoluții empirice. Acesta este motivat de antagonist să își depășească limitele, să contrasteze prin valori morale pozitive, să dea dovadă de bunătate și să își desăvârșească evoluţia. Eroul lui I. Creangă este unul atipic, demonstrând o latură umană într-o lume a simbolurilor și entităților fantastice, detașându-se de protagoniștii tipici basmelor printr-un portret complex, realist, care pune accent pe intuiția umană în detrimentul calităților supraomenești.

Tema principală este maturizarea mezinului craiului, fiind ilustrată aventura eroică, un drum al maturizării tânărului, necesar pentru dobândirea condiției de împărat, în raport continuu cu mentorul său. Motive specifice basmelor sunt întâlnite și în opera lui Ion Creangă, precum împăratul fără urmași, superioritatea mezinului, călătoria, supunerea prin vicleșug, demascarea răufăcătorului, pedeapsa, căsătoria.

Titlul operei îl are în centru pe erou, personajul eponim, al cărui nume sugerează parcursul pe care acesta îl va avea de-a lungul desfășurării acțiunii, cât și condiția sa duală. Prin alăturarea secvenței ”Povestea lui” se face referire la specie, subliniind caracterul oral al operei. Harap-Alb este, însă, un nume dobândit, reliefând astfel rolul didactic al povestirii. Oximoronul redat de simbolurile cromatice ale cuvintelor ”harap”, persoană cu pielea de culoare închisă, și ”alb”, ilustrează evoluția de la stadiul de novice la cel de prinț, cât și diferența între ipostaza sa de slugă versus statutul de nobil.

Întâmplările basmului sunt prezentate dintr-o perspectivă narativă obiectivă de către un narator omniscient, omniprezent, dar a cărui subiectivitate se face simțită prin comentariile și intervențiile făcute de-a lungul operei, caracterizate de note umoristice.

Conflictul, ca în orice basm, este constituit de lupta binelui împotriva răului, detașându-se formele pe care aceste două valori le întruchipează în operă. Binele nu este o valoare absolută, un personaj justițiar, ci un tânăr cu defecte și calități, dar cu o voință și un caracter de neînvins. Acesta dezvoltă simțul dreptății, empatia și altruismul, pe parcursul călătoriei sale devenind o persoană nouă, obținând la final titlul de inițiat. Exponentul răului este tot o ființă umană înzestrată cu o inteligență vicleană, ce se prezintă sub două forme: Spânul și Împăratul Roș. Aceste personaje sunt esențiale în procesul de maturizare a eroului întrucât reprezintă un rău necesar.

Harap-Alb dispune de o tipologie caracteristică, acesta fiind exponentul binelui sub forma protagonistului. Ambiguizarea sa îl determină să nu fie o întruchipare absolută a forţelor pozitive, având slăbiciuni și defecte specific umane. Statuturile pe care le dobândește de-a lungul poveștii îi definesc comportamentul și îi influențează relația cu celelalte personaje. La început, eroul are statutul de mezin neinițiat, fiu de crai, urmând ca pe parcurs acesta să capete statutul de slugă, corespondent numelui de ”Harap-Alb”, iar în final să devină Împărat. Acest proces este rezultatul drumului inițiatic și al căutării de sine, ce fac din protagonist un personaj rotund, rezultat care nu ar fi fost posibil în absența personajului antagonic care să îl motiveze pe erou și să îi dezvolte calitățile.

Personajul este caracterizat atât în mod direct de autor prin intermediul descrierii, dar și în mod indirect prin acțiuni, nume, relația cu alte personaje sau limbaj. Portretul fizic al eroului este slab conturat, accentul povestirii căzând pe evoluția sa morală în cadrul drumului inițiatic, al transformării sale din novice în împărat.

Din punct de vedere moral, portretul psihologic al protagonistului este conturat în mod direct prin prisma celorlalte personaje. Astfel, tatăl său îl consideră ”vrednic de împărat” și îl felicită - ”bun cap ai avut”, demonstrându-și mândria și afecțiunea față de reușita lui; Sfânta Duminică îl consideră ”mai fricos decât o femeie” pentru a-i sublinia naivitatea, dar afirmă că ”puterea milosteniei și inima ta cea bună te ajută”; cele două crăiese îi apreciază altruismul ”ești așa de bun”; verișoarele sale consideră că ”are o înfățișare mult mai plăcută și seamănă a fi mult mai omenos”, însă Spânul îl consideră întotdeauna inferior numindu-l ”fecior de om viclean”, ”pui de viperă” sau ”slugă netrebnică”.

Cele mai reprezentative pentru conturarea trăsăturilor lui de caracter sunt, însă, acțiunile întreprinse de erou, mod indirect de caracterizare. Sufletul pur și onest al tânărului este subliniat în repetate rânduri, acesta confruntându-se cu alegeri importante pe care le ia în spiritul dreptății și corectitudinii. În relația cu celelalte personaje, se dovedește a fi milos față de Sfânta Duminică, drept, păstrează jurământul de loialitate față de Spân, urmându-i fiecare poruncă, şi descoperă adevărata esență a ființei umane și a prieteniei atunci când se întovărășește cu cele 5 ajutoare.

Evoluția în planul caracterului este sincronizată cu parcurgerea drumului de inițiere, la finalul căruia eroul trebuie să treacă într-un plan superior de existență. O secvență semnificativă este despărțirea de tatăl său, după câștigarea probei inițiale. Acesta se arată mândru de fiul său datorită alegerilor pe care le face, felicitându-l: ”tu ești vrednic de împărat”, dar și avertizându-l să se ferească ”de omul roș, iară mai ales de cel spân”. Acesta este un episod semnificativ întrucât reprezintă plecarea în lume a mezinului, urmată de încălcarea spuselor tatălui din cauza lipsei de experiență.

În episodul coborârii în fântână, naratorul surprinde lipsa de inițiere a tânărului, care ”boboc în felul său” cae în capcana întinsă. Spânul îl închide în fântână și îi cere, pentru a-l lăsa în viață, să facă schimb de identitate, să devină robul lui și să jure ”pe ascuțitul paloșului” să-i dea ascultare, condiționând însă paradoxal această legătură ”până va muri și iar va învia”. Acest jurământ introduce o nouă etapă în evoluția eroului, în care acesta devine din fiu de împărat slugă, primind numele de Harap-Alb.

Ajunși la curtea lui Verde-Împărat, Spânul îl supune pe Harap-Alb la trei probe semnificative pentru dezvoltarea eroului, și anume aducerea ”salăților” din Grădina Ursului, aducerea pieii cerbului cu ”pietre scumpe” și a fetei Împăratului Roș. Mijloacele prin care eroul trece probele țin de miraculos, ajutoarele sale - Crăiasa Albinelor, furnica zburătoare, cei cinci tovarăși - având puteri supranaturale. Pentru protagonist, aducerea fetei Împăratului Roș la Spân este cea mai dificilă încercare deoarece pe drum se îndrăgostește de ea. Onest fiind, își respectă jurământul făcut și nu îi mărturisește adevărata sa identitate. Spânul însă nu poate concepe demascarea, astfel că îi taie capul eroului, înfăptuind astfel ruperea înțelegerii și implicit încheierea inițierii. Eroul este înviat de fată cu ajutorul obiectelor magice, precum ”trei smicele de măr dulce, apă vie și apă moartă”. El reintră în posesia paloșului și primește răsplata finală: pe fata Împăratului Roș și împărăția, dobândind statutul de împărat.

În concluzie, ”Povestea lui Harap-Alb” propune un nou tip de erou al universului basmelor, unul complex, multidimensional, rotund, caracterizat de trăsături umane care-l evidențiază, precum bunătate și curaj, a cărui personalitate este conturată printr-un proces de maturizare, conferind textului caracter de bildungsroman.`,
};