
export default {
        title: "Luceafărul - context și analiză",
        text: `Poemul Luceafărul a apărut în 1883, în Almanahul Societăţii Academice Social-Literare România Jună din Viena, fiind apoi reprodus în revista Convorbiri literare.
 
Poemul este inspirat din basmul românesc Fata în grădina de aur, cules de austriacul Richard Kunisch. Basmul cuprindea povestea unei frumoase fete de împărat izolată de tatăl ei într-un castel, de care se îndrăgosteşte un zmeu. Fata însă se sperie de nemurirea zmeului şi-l respinge. Zmeul merge la Demiurg, doreşte să fie dezlegat de nemurire, dar este refuzat. Întors pe pământ, zmeul o vede pe fată, care între timp se îndrăgostise de un pământean, un fecior de împărat, cu care fugise în lume. Furios, zmeul se răzbună pe ei şi îi desparte prin vicleşug. Peste fată el prăvăleşte o stâncă, iar pe feciorul de împărat îl lasă să moară în Valea Amintirii.
 
Eminescu valorifică iniţial acest basm în perioada studiilor berlineze, într-un poem intitulat tot Fata în grădina de aur, dar modifică finalul. Răzbunarea nu i se pare potrivită cu superioritatea fiinţei nemuritoare, aşa că zmeul din poemul lui Eminescu rosteşte cu amărăciune către cei doi pământeni: „Fiţi fericiţi - cu glasu-i stins a spus - / Atât de fericiţi, cât viaţa toată/ Un chin s-aveţi - de-a nu muri deodată."
 
Între 1880 şi 1883, poemul este prelucrat în cinci variante succesive, schema epică devenind pretextul alegoric al meditaţiei romantice.
 
Alături de sursele folclorice ale poemului (basmele prelucrate: Fata-n grădina de aur, Miron şi frumoasa fără corp şi mitul zburătorului), poetul valorifică surse mitologice şi izvoare filozofice (antinomiile dintre geniu şi omul comun, din filozofia lui Arthur Schopenhauer).
 
IPOTEZA: Poemul romantic Luceafărul de Mihai Eminescu este o alegorie pe tema geniului, dar şi o meditaţie asupra condiţiei umane duale (omul supus unui destin pe care tinde să îl depăşească).
 
Cea mai veche interpretare a poemului îi aparţine lui Eminescu însuşi, care nota pe marginea unui manuscris: „În descrierea unui voiaj în Ţările române, germanul K. (Kunisch) povesteşte legenda Luceafărului. Aceasta este povestea. Iar înţelesul alegoric ce i-am dat este că, dacă geniul nu cunoaşte nici moarte şi numele lui scapă de noaptea uitării, pe de altă parte el pe pământ nici e capabil de a ferici pe cineva, nici capabil de a fi fericit. El n-are moarte, dar n-are nici noroc."
 
Din acest punct de vedere, Luceafărul poate fi considerat o alegorie pe tema romantică a locului geniului în lume, ceea ce înseamnă că povestea, personajele, relaţiile dintre ele sunt transpuse într-o suită de metafore, personificări şi simboluri. Poemul reprezintă o meditaţie asupra destinului geniului în lume, văzut ca o fiinţă solitară şi nefericită, opusă omului comun.
 
O altă interpretare (Tudor Vianu) socoteşte „personajele" poemului drept „voci" ale poetului, măştile lui, în sensul că eul poetic se proiectează în diverse ipostaze lirice, corespunzătoare propriilor contradicţii. Privind astfel lucrurile, se poate spune că poetul s-a proiectat nu numai sub chipul lui Hyperion - geniul, ci şi sub chipul lui Cătălin, reprezentând aspectul teluric al bărbatului, sau al Demiurgului, exprimând aspiraţia spre impersonalitatea universală, şi chiar sub chipul Cătălinei, muritoarea care tânjeşte spre absolut.
 
Poemul e de substanţă lirică cu schemă epică, ţesute în structura dramatică, ce accentuează lirismul. Schema epică a poemului este reprezentată de elementul narativ preluat din basm şi care e pretext pentru reflecţia filosofică. Caracterul dramatic este conferit de succesiunea de scene ale structurii, unde dialogul predomină. Intensitatea trăirilor sufleteşti ţine tot de caracterul dramatic al poemului. Substanţa lirică provine din faptul că poemul proiectează problematica geniului în raport cu societatea, iubirea şi cunoaşterea. În esenţă, poemul este un monolog liric, dialogul accentuând înălţimea ideilor care-i conferă caracterul filozofic.
 
Viziunea romantică e dată de structură, de temă, de relaţia geniu-societate, de cosmogonii, de alternarea planului terestru cu planul cosmic, de motivul luceafărului, de amestecul speciilor (elegie, meditaţie, idilă, pastel), de metamorfozele lui Hyperion. Elementele clasice sunt: echilibrul compoziţional, simetria, armonia şi caracterul gnomic.
 
Tema poemului este romantică: problematica geniului în raport cu lumea, iubirea şi cunoaşterea. Compoziţional, Luceafărul este structurat în patru părţi. În prima şi în ultima parte, cele două planuri, terestru şi cosmic, interferează, pe când în părţile a doua şi a treia, ele se separă net, partea a doua fiind consacrată planului terestru, Cătălinei ce acceptă iubirea lui Cătălin, iar partea a treia planului cosmic, unde Demiurgul îi dezvăluie lui Hyperion motivele pentru care nu poate da curs rugăminţii de a-l transforma în muritor.
 
Începutul poemului se află sub semnul basmului. Timpul este anistoric, mitic (illo tempore): „A fost odată ca-n poveşti/ A fost ca niciodată". Cadrul abstract este umanizat. Portretul fetei de împărat, realizat prin superlativul absolut de factură populară „o prea frumoasă fată", scoate în evidenţă o autentică unicitate terestră. Fata de împărat reprezintă pământul însuşi, iar comparaţiile: „Cum e Fecioara între sfinţi/ Şi luna între stele" propun o posibilă dualitate: puritate şi predispoziţie spre înălţimile astrale.
 
Partea întâi: Primele şapte strofe constituie uvertura poemului, partea întâi fiind o splendidă poveste de iubire, unde atmosfera este în concordanţă cu mitologia română, iar imaginarul poetic e de factură romantică. Fata de împărat e văzută în mişcare abia perceptibilă, pentru că totul se petrece în planul visului. Fata contemplă Luceafărul de la fereastra dinspre mare a castelului. La rându-i, Luceafărul, privind spre „umbra negrului castel", o îndrăgeşte pe fată şi se lasă copleşit de dor.
 
Semnificaţia alegoriei este că fata pământeană aspiră spre absolut, iar spiritul superior simte nevoia compensatorie a materialităţii. Pe de altă parte, iubirea fetei are un accent de cotidian, conferit de construcţia simetrică „îl vede azi, îl vede mâni/ Astfel dorinţa-i gata". În antiteză, iubirea Luceafărului are nevoie de un lung proces de „cristalizare", cum ar spune Stendhal: „El iar privind de săptămâni/ Îi cade dragă fata." Cadrul este întunecat, nocturn, specific romantic, favorabil visului.
 
Motivul serii şi al castelului accentuează romantismul conferit de prezenţa Luceafărului: „Şi cât de viu s-aprinde el/ În orişicare sară,/ Spre umbra negrului castel/ Când ea o să-i apară". Mişcările sunt de mare fineţe şi au loc în plan oniric, dezvăluind suavitatea sentimentului de iubire exprimat prin motivul zburătorului: „Şi pas cu pas în urma ei/ Alunecă-n odaie".
 
Planul terestru alternează cu cel cosmic: „Şi când în pat se-ntinde drept/ Copila să se culce,/ I-atinge mâinile pe piept,/ I-nchide geana dulce". Motivul zburătorului apare alături de simbolul oglinzii.
 
Ca şi în Floare albastră sau în Dorinţa, atracţia îndrăgostiţilor unul pentru celălalt este sugerată mai întâi de o chemare, menită să scoată în evidenţă dorul şi puterea sentimentului. La chemarea fetei: „O, dulce-al nopţii mele domn,/ De ce nu vii tu? Vină!", Luceafărul se smulge din sfera sa, spre a se întrupa prima oară din cer şi mare, asemenea lui Neptun (în concepţia lui Platon), ca un „tânăr voievod", totodată „un mort frumos cu ochii vii". În această ipostază angelică, Luceafărul are o frumuseţe construită după canoanele romantice: „păr de aur moale", „umerele goale", „umbra feţei străvezii".
 
În contrast cu paloarea feţei sunt ochii, care ilustrează prin scânteiere viaţa interioară. Strălucirea lor este interpretată de fată ca semn al morţii: „Luceşti fără de viaţă [...]/ Şi ochiul tău mă-ngheaţă". Ea înţelege incandescenţa din ochii Luceafărului ca semn al glacialităţii şi refuză să-l urmeze. Luceafărul, în schimb, vrea să-i eternizeze iubirea: „Colo-n palate de mărgean/ Te-oi duce veacuri multe,/ Şi toată lumea-n ocean/ De tine o s-asculte."
 
Urmând repetatei chemări-descântec: „Coboară în jos, luceafăr blând,/ Alunecând pe-o rază", cea de-a doua întrupare va fi din soare şi noapte. Cosmogonia este redată în tonalitate majoră: „Iar ceru-ncepe a roti/ În locul unde piere". În antiteză cu imaginea angelică a primei întrupări, aceasta este circumscrisă demonicului, după cum o percepe fata: „O, eşti frumos, cum numa-n vis/ Un demon se arată".
 
Imaginea se înscrie tot în canoanele romantismului: părul negru, „marmoreele braţe", „ochii mari şi minunaţi". Pentru a doua oară, paloarea feţei şi lucirea ochilor, semne ale dorinţei de absolut, sunt înţelese de fată ca atribute ale morţii: „Privirea ta mă arde". Deşi unică între pământeni, fata refuză din nou să-l urmeze: „Dară pe calea ce-ai deschis/ N-oi merge niciodată!", recunoscând că nu poate răspunde cu aceeaşi intensitate pasiunii lui şi că nu-l poate înţelege: „Deşi vorbeşti pe înţeles/ Eu nu te pot pricepe". Dragostea lor semnifică atracţia contrariilor.
 
Luceafărul formulează sintetizator diferenţa care-i separă: „eu sunt nemuritor,/ Şi tu eşti muritoare", dar, din iubire, acceptă supremul sacrificiu cerut de fată, prin aceasta afirmându-şi superioritatea faţă de ea. Dacă fata/omul comun nu se poate înălţa la condiţia nemuritoare, Luceafărul/geniul este capabil, din iubire şi din dorinţa de cunoaştere absolută, să coboare la condiţia de muritor: „Da, mă voi naşte din păcat/ Primind o altă lege;/ Cu vecinicia sunt legat,/ Ci voi să mă dezlege".
 
Partea a doua: idila dintre fata de împărat, numită acum Cătălina, şi pajul Cătălin, simbolizează repeziciunea cu care se stabileşte legătura sentimentală între exponenţii lumii terestre. Este o altă ipostază a iubirii, opusă celei ideale. Asemănarea numelor sugerează apartenenţa la aceeaşi categorie: a omului comun. Cătălina recunoaşte asemănarea, dincolo de statutul social: „Încă de mic/ Te cunoşteam pe tine,/ Şi guraliv şi de nimic,/ Te-ai potrivi cu mine...".
 
Portretul lui Cătălin este realizat în stilul vorbirii populare, în antiteză cu portretul Luceafărului, pentru care motivele şi simbolurile romantice erau desprinse din mit, abstracte, exprimând nemărginirea, infinitul, eternitatea. Aşadar Cătălin devine întruchiparea telu­ricului, a mediocrităţii pământene: „viclean copil de casă", „Băiat din flori şi de pripas,/ Dar îndrăzneţ cu ochii", „cu obrăjei ca doi bujori". Ca mod de expunere predominant este dialogul. Idila se desfăşoară sub forma unui joc.
 
Cei doi formează un cuplu norocos şi fericit, supus legilor pământene, deosebite de legea după care trăieşte Luceafărul. Chiar dacă acceptă iubirea pământeană, Cătălina aspiră încă la iubirea ideală pentru Luceafăr: „O, de luceafărul din cer/ M-a prins un dor de moarte". Acest „dor de moarte" ilustrează dualitatea fiinţei pământene, aspiraţia specific umană spre absolut, dar şi atracţia către fiinţa inaccesibilă. Pasiunea ei este generată şi de obstacolul impus de apartenenţa la condiţii diferite, de dorinţa specific romantică de a transforma imposibilul în posibil: „Dar se înalţă tot mai sus,/ Ca să nu-l pot ajunge.// Pătrunde trist cu raze reci/ Din lumea ce-l desparte.../ În veci îl voi iubi şi-n veci/ Va rămânea departe...".
 
Puterea de sacrificiu a omului de geniu în numele împlinirii idealului absolut este ilustrată de intensitatea sentimentului de iubire, care duce la renunţarea la nemurire.
 
Partea a treia ilustrează planul cosmic şi constituie cheia de boltă a poemului. Această parte poate fi divizată la rândul ei în trei secvenţe poetice: zborul cosmic, rugăciunea, convorbirea cu Demiurgul şi liberarea.
 
Spaţiul parcurs de Luceafăr este o călătorie regresivă temporal, în cursul căreia el trăieşte în sens invers istoria creaţiunii: „Şi din a chaosului văi,/ Jur împrejur de sine,/ Vedea, ca-n ziua cea de-ntâi,/ Cum izvorau lumine". Zborul cosmic potenţează intensitatea sentimentelor, lirismul, setea de iubire ca act al cunoaşterii absolute. Amplificarea acestui zbor culminează cu imaginea Luceafărului ca fulger („Părea un fulger ne-ntrerupt/ Rătăcitor prin ele"), amintind dinamismul luminii, pură energie surprinsă în curgerea ei prin timp şi spaţiu. Punctul în care el ajunge este spaţiul demiurgic, atemporal, momentul dinaintea naşterii lumilor: „Căci unde-ajunge nu-i hotar,/ Nici ochi spre a cunoaşte,/ Şi vremea-ncearcă în zadar/ Din goluri a se naşte".
 
În dialogul cu Demiurgul, Luceafărul însetat de repaos: „Şi din repaos m-am născut,/ Mi-e sete de repaos", adică de viaţă finită, de stingere, este numit Hyperion (nume de sugestie mitologică, gr. cel care merge pe deasupra). După Hesiod, Hyperion, divinitate simbolică, era fiul Cerului, tatăl Soarelui şi al Lunii, un titan ucis din invidie de alţi titani. După Homer, Hyperion este Soarele însuşi. De remarcat că Demiurgul este cel care rosteşte pentru întâia oară numele lui Hyperion; Demiurgul este cel care afirmă şi cunoaşte cu adevărat identitatea Luceafărului, idee ce accentuează subordonarea acestuia din urmă faţă de Demiurg.
 
Hyperion îi cere Demiurgului să-l dezlege de nemurire pentru a descifra taina iubirii absolute, în numele căreia este gata de sacrificiu: „Reia-mi al nemuririi nimb/ Şi focul din privire,/ Şi pentru toate dă-mi în schimb/ O oră de iubire...". Demiurgul refuză cererea lui Hyperion. Constantin Noica observă că Hyperion cere să devină altceva, dar ca să fie altceva trebuie să se nască din nou. Luceafărul însă se născuse o dată cu lumea. Aspiraţia lui este imposibilă, căci el face parte din ordinea primordială a cosmosului, iar ruperea sa ar duce din nou la haos. Demiurgul nu-i poate oferi moartea pentru că astfel ar produce moartea lumii, ceea ce ar coincide cu negarea de sine.
 
Demiurgul îi explică Luceafărului absurditatea dorinţei lui, prilej cu care este pusă în antiteză lumea nemuritorilor şi aceea a muritorilor. Astfel, muritorii nu-şi pot determina propriul destin, se bazează numai pe noroc şi sunt supuşi voinţei oarbe de a trăi (influenţa filozofiei lui Schopenhauer). Omul de geniu, în schimb, este capabil de a împlini idealuri înalte, se află dincolo de timp şi de spaţiu, dincolo de ordinea firească a lumii: „Ei doar au stele cu noroc/ Şi prigoniri de soarte,/ Noi nu avem nici timp, nici loc,/ Şi nu cunoaştem moarte". Omul se află sub puterea unui destin implacabil căruia nu i se poate sustrage, ceea ce-i dă imposibilitatea de a trece din lumea materială în cea spirituală: „Părând pe veci a răsări,/ Din urmă moartea-l paşte,/ Căci toţi se nasc spre a muri/ Şi mor spre a se naşte".
 
În schimb, Demiurgul îi propune lui Hyperion diferite ipostaze ale geniului: a verbului, a cuvântului creator („Cere-mi - cuvântul meu de-ntâi,/ Să-ţi dau înţelepciune?"); ipostaza orfică („Vrei să dau glas acelei guri,/ Ca dup-a ei cântare/ Să se ia munţii cu păduri/ Şi insulele-n mare?"); ipostaza împăratului („Ţi-aş da pământul în bucăţi/ Să-l faci împărăţie"); a geniului militar, a cezarului („Îţi dau catarg lângă catarg,/ Oştiri spre a străbate/ Pămăntu-n lung şi marea-n larg"). Demiurgul păstrează pentru final argumentul zdrobitor, dovedindu-i încă o dată Luceafărului superioritatea sa, chiar şi în iubire, faţă de muritoarea Cătălina: „Şi pentru cine vrei să mori?/ Întoarce-te, te-ndreaptă/ Spre-acel pământ rătăcitor/ Şi vezi ce te aşteaptă".
 
Partea a patra este construită simetric faţă de prima, prin interferenţa celor două planuri: terestru şi cosmic. Idila Cătălin-Cătălina are loc într-un cadru romantic, creat prin prezenţa simbolurilor specifice. Peisajul este umanizat, specific eminescian, scenele de iubire se petrec departe de lume, sub crengile de tei înflorite, în singurătate şi linişte, în pacea codrului, sub lumina blândă a lunii.
 
Declaraţia de dragoste a lui Cătălin, pătimaşa lui sete de iubire exprimată prin metaforele: „noaptea mea de patimi", „durerea mea", „iubirea mea de-ntâi", „visul meu din urmă", îl proiectează pe acesta într-o altă lumină decât aceea din partea a doua a poemului. Profunzimea pasiunii şi unicitatea iubirii, constituirea cuplului adamic, îl scot pe Cătălin din ipostaza terestră: „Miroase florile-argintii/ Şi cad, o dulce ploaie,/ Pe creştetele-a doi copii/ Cuplete lungi, bălaie".
 
„Îmbătată de amor", Cătălina are încă nostalgia astrului iubirii şi-i adresează pentru a treia oară chemarea, de data aceasta modificată, Luceafărul semnificând acum steaua norocului: „Coboară în jos, luceafăr blând,/ Alunecând pe-o rază,/ Pătrunde-n codru şi în gând,/ Norocu-mi luminează!".
 
Luceafărul exprimă dramatismul propriei condiţii, care se naşte din constatarea că relaţia om-geniu este incompatibilă. Atitudinea geniului este una de interiorizare a sinelui, de asumare a eternităţii şi o dată cu ea a indiferenţei, a ataraxiei stoice. Omul comun este incapabil să-şi depăşească limitele, iar geniul manifestă un profund dispreţ faţă de această incapacitate: „Ce-ţi pasă ţie, chip de lut,/ Dac-oi fi eu sau altul?". Geniul constată cu durere că viaţa cotidiană a omului urmează o mişcare circulară, orientată spre accidental şi întâmplător: „Trăind în cercul vostru strâmt/ Norocul vă petrece,/ Ci eu în lumea mea mă simt/ Nemuritor şi rece".
 
Nivelul fonetic şi prozodic: conservarea unui ă etimologic, prezent în graiurile moldoveneşti şi ardeleneşti („Cum ea pe coate-şi râzimă"); vocala finală neaccentuată e este redată prin ă după consoane dure („marmoreele braţă"); î etimologic, conservat în graiul moldovenesc („Şi tainic genele le plec/ Căci mi le împle plânsul"); utilizarea unor fonetisme conservate în graiul moldovenesc şi ardelenesc conferă blândeţea sonorităţii. Antiteza dintre planul terestru şi cel cosmic este sugerată de alternarea tonului minor cu cel major, realizată prin distribuţia consoanelor şi a vocalelor; muzicalitatea elegiacă, meditativă, este dată şi de particularităţile prozodice: ritmul iambic, rima încrucişată, măsura versurilor de 7-8 silabe; sunt prezente asonantele şi rima interioară (luna - una, zare - răsare, plec - împle).
 
Nivelul morfologic: dativul etic şi dativul posesiv susţin tonul de intimitate; interjecţii, în dialogul Cătălin-Cătălina: „măr", „ia"; abundenţa verbelor la imperativ în strofele ce constituie chemările fetei, forme verbale ce dau tonul de îndrăgire şi ardoare: „coboară", „pătrunde", „luminează"; formele arhaice ale unor verbe accentuează atmosfera fabuloasă specifică basmului: „Şi apa unde-a fost căzut"; verbele la imperfect, în episodul călătoriei Luceafărului în spaţiul cosmic, denotă mişcarea eternă şi continuă: „creşteau", „treceau", „părea", „vedea"; verbele la perfect simplu şi la conjunctiv din tabloul al doilea susţin oralitatea stilului, vorbirea populară specifică oamenilor de aceeaşi condiţie: „se făcu", „să razi", „să-mi dai".
 
Nivelul stilistic: antiteza structurală; alegoria pe baza căreia este construit poemul; epitete ornante: „Uşor el trece ca pe prag"; prezenţa metaforelor, mai ales în primul tablou, în cadrul dialogului dintre Luceafăr şi fata de împărat, accentuează ideea iubirii absolute ce se cere eternizată într-un cadru pe măsură: „palate de mărgean", „cununi de stele"; metafore sinestezice în cadrul primului tablou: „Şi ochii mari şi grei mă dor,/ Privirea ta mă arde"; imagini hiperbolice în portretizarea Luceafărului: „Venea plutind în adevăr/ Scăldat în foc de soare"; metonimii utilizate în pasaje cu sens aforistic, în discursul Demiurgului: „Îţi dau catarg lângă catarg/ Oştiri spre a străbate"; comparaţii construite prin asocierea unor termeni abstracţi, în prezentarea călătoriei Luceafărului în spaţiul cosmic: „E un adânc asemenea/ Uitării celei oarbe"; antiteza între omul de geniu şi oamenii comuni, antiteză pe baza căreia îşi construieşte discursul Demiurgul: „Ei doar au stele cu noroc/ Şi prigoniri de soarte,/ Noi nu avem nici timp, nici loc,/ Şi nu cunoaştem moarte"; oximoronul ce ia un aspect apropiat de antiteză: „Ţesând cu recile-i scântei/ O mreajă de văpaie".
 
CONCLUZIA: Pentru ilustrarea condiţiei geniului, poemul Luceafărul - sinteză a operei poetice eminesciene - armonizează atât teme, motive, elemente de imaginar poetic, atitudini romantice, procedee artistice cultivate de scriitor, cât şi simbolurile eternităţii/morţii şi ale temporalităţii/vieţii.`,

}